"""Shared database exports for records and repository contracts."""

from .records import (
    AdapterEventActionRecord,
    AdapterEventRecord,
    ChatPatternCandidateRecord,
    ChatPatternSeedRecord,
    ChannelRecord,
    PatternRecord,
    RecentMessageRecord,
    ReplyRecord,
    SupportTicketRecord,
    ThreadRecord,
    TrackedChannelStateRecord,
    TrackedUserRecord,
    TwitchAccountRecord,
    TwitchDeviceFlowRecord,
    TwitchUserCacheRecord,
    UserPermissionRecord,
)
from .repositories import (
    AdapterEventActionRepository,
    AdapterEventRepository,
    ChannelRepository,
    MessageRepository,
    PatternRepository,
    ReplyRepository,
    SupportTicketRepository,
    ThreadRepository,
    TrackedUserRepository,
    TwitchAccountRepository,
    TwitchDeviceFlowRepository,
    TwitchUserCacheRepository,
    UserPermissionRepository,
)

__all__ = [
    "AdapterEventActionRecord",
    "AdapterEventActionRepository",
    "AdapterEventRecord",
    "AdapterEventRepository",
    "ChatPatternCandidateRecord",
    "ChatPatternSeedRecord",
    "ChannelRecord",
    "ChannelRepository",
    "MessageRepository",
    "PatternRecord",
    "PatternRepository",
    "RecentMessageRecord",
    "ReplyRecord",
    "ReplyRepository",
    "SupportTicketRecord",
    "SupportTicketRepository",
    "ThreadRecord",
    "ThreadRepository",
    "TrackedChannelStateRecord",
    "TrackedUserRecord",
    "TrackedUserRepository",
    "TwitchAccountRecord",
    "TwitchAccountRepository",
    "TwitchDeviceFlowRecord",
    "TwitchDeviceFlowRepository",
    "TwitchUserCacheRecord",
    "TwitchUserCacheRepository",
    "UserPermissionRecord",
    "UserPermissionRepository",
]
